### ISSUE TITLE
Add templates

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-graphite#71]
This is an ongoing list of check plugins that need templates, plugins without performance data may be left out:

- [x] apt
- [ ] clamd
- [x] dhcp
- [x] dig
- [x] disk
- [x] dns
- [x] file_age
- [x] fping
- [x] fping4
- [x] fping6
- [x] ftp
- [x] hostalive
- [x] http
- [x] icmp
- [x] imap
- [x] ldap
- [x] load
- [x] mailq
- [ ] memory ([stalled](https://github.com/Icinga/icingaweb2-module-graphite/issues/71#issuecomment-345759988))
- [x] mysql
- [x] mysql_health
- [ ] ~mysql_query~ (1)
- [ ] ~nscp~ (1)
- [x] ntp_peer
- [x] ntp_time
- [x] pgsql
- [x] ping
- [x] ping4
- [x] ping6
- [x] procs
- [x] smtp
- [ ] ~snmp~ (1)
- [x] snmp-uptime
- [ ] ~snmpv3~ (1)
- [x] ssh
- [ ] ~ssl~ (2)
- [x] swap
- [x] tcp
- [x] udp
- [ ] ups ([stalled](https://github.com/Icinga/icinga2/issues/6071))
- [x] users
- [x] disk-windows
- [x] load-windows
- [x] memory-windows
- [x] network-windows
- [ ] ~perfmon-windows ([stalled](https://github.com/Icinga/icingaweb2-module-graphite/issues/71#issuecomment-357228479))~ (1)
- [x] ping-windows
- [x] proms-windows
- [ ] ~service-windows ([stalled](https://github.com/Icinga/icingaweb2-module-graphite/issues/71#issuecomment-357228772))~ (https://github.com/Icinga/icingaweb2-module-graphite/issues/71#issuecomment-358952213)
- [x] swap-windows
- [x] update-windows
- [x] uptime-windows
- [x] users-windows

## Footnotes

1. :
    * no useful legend and Y axis unit prefix possible
    * handled by the default template
2. No perfdata to graph

## Subtasks

* [x] #85

**Comment by naksitrallid** [comment]
some basic templates i made and use

for DNS response time:
```
[dns-time.graph]
check_command = "dns"

[dns-time.metrics_filters]
value = "$service_name_template$.perfdata.time.value"

[dns-time.urlparams]
title = "DNS response time"
areaMode = "first"
areaAlpha = "0.3"

[dns-time.functions]
value = "alias(color($metric$, 'orange'), 'Response time')"
```
for NTP offset:
```
[ntp.graph]
check_command = "ntp_peer"

[ntp.metrics_filters]
offset.value = "$service_name_template$.perfdata.offset.value"

[ntp.urlparams]
title = "NTP Offset"
areaMode = "all"
areaAlpha = "0.4"

[ntp.functions]
offset.value = "alias(color($metric$, 'blue'), 'NTP Offset')"
```
for SMTP response time:
```
[smtp-time.graph]
check_command = "smtp"

[smtp-time.metrics_filters]
value = "$service_name_template$.perfdata.time.value"

[smtp-time.urlparams]
title = "SMTP response time"
areaMode = "first"
areaAlpha = "0.3"

[smtp-time.functions]
value = "alias(color($metric$, 'orange'), 'Response time')"
```

**Comment by Al2Klimov** [comment]
Hello @naksitrallid and thank you for your suggestion.

Feel free to open a pull request.

However I'd like you (and any other contributor to this issue) to wait with opening pull requests until #60 has been merged as it introduces changes to the already existing templates. Please also see those changes as a guideline so that all graphs you contribute adapt to the existing ones. While you comply to this, please note that different kinds of graphs have different color schemes etc..

Best,
AK

**Comment by Al2Klimov** [comment]
"plugins without performance data may be left out" – @bobapple

No, "plugins without performance data" *must* be left out as they don't provide any graphs and they're assembled only from performance data.

**Comment by Al2Klimov** [comment]
@lippserd IMO it makes sense to assign this non-critical task to a "non-key-person" (if U No what I mean). They can learn something about this module and I have more time for the more critical stuff.

**Comment by Al2Klimov** [comment]
* after #60!

**Comment by Al2Klimov** [comment]
As discussed w/ @nilmerg (offline):

Both of us start working on this ASAP and ticking the written templates, he starts from the bottom and I from the top.

**Comment by Al2Klimov** [comment]
Notice for @nilmerg and me:

https://github.com/monitoring-plugins/monitoring-plugins/blob/master/plugins

**Comment by Al2Klimov** [comment]
@nilmerg

```
object Host "dummy" {
	import "generic-host"

	vars.demoperfdatasvcs = {
		"apt" = "available_upgrades=4;;;0 critical_updates=2;;;0"
	}
}

object CheckCommand "demoperfdata" {
	command = [ "/bin/printf", "Dummy perfdata |%s", "$demoperfdata$" ]
}

apply Service for (svc => perfdata in host.vars.demoperfdatasvcs) {
	import "generic-service"
	check_interval = 10s
	check_command = "demoperfdata"
	vars.demoperfdata = perfdata
	vars.check_command = svc
}
```

Add one line per check command to `vars.demoperfdatasvcs` to view graphs in the UI.

(Special thx 2 @dnsmichi)

**Comment by Al2Klimov** [comment]
See also https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins

**Comment by Al2Klimov** [comment]
@nilmerg Please write down the commands here if you discover any made-in-Germany perfdata ("0,0" instead of "0.0"). (Maybe I'll make some pull requests.)

**Comment by Al2Klimov** [comment]
made-in-Germany:
* dig
* fping4

**Comment by Al2Klimov** [comment]
As investigated w/ @Crunsher:

1. there is a `check_`**`mem`**`.pl` in the ITL, but no `check_`**`memory`**
2. there is a `check_`**`memory`** at Icinga Exchange

CC @bobapple

**Comment by Al2Klimov** [comment]
@bobapple Btw. I think it would be a good idea not to write any templates for "non-standard" plugins which aren't shipped by monitoring-plugins, nor nagios-plugins, nor nagios-plugins-contrib, nor our icinga2x Vagrant demo box. Do you think it's neccessary to write a template for a plugin "just" because it's in the ITL?

"People contribute Icinga 2 config for various check plugins to the ITL from time to time."
– @Crunsher

**Comment by Al2Klimov** [comment]
@nilmerg Forget about the "made in Germany" plugins. Actually they render floats locale-dependend, but Icinga 2 (or whatever above it) sets LC_ALL to prevent bad thing in production.

**Comment by dnsmichi** [comment]
Icinga 2 does that, `LC_NUMERIC=C`.

**Comment by Al2Klimov** [comment]
@dnsmichi Cool.

**Comment by Al2Klimov** [comment]
Before I write the template for `perfmon-windows`, I'd like to see one or more (more would be better) real world usages (plugin outputs w/ perfdata – monitored objects config doesn't matter). If you read this, please provide some. Feel free to censor our clients' names or similar.

Hints:
1. The more perfdata per plugin output, the better
2. The more different "things" (e.g. disks, NICs, ...) per plugin output, the better (if applicable)
3. If you were mentioned in this comment and can't provide what I requested, please just don't write anything at all. There are already enough comments in this thread and this shall be not a chain letter.

CC @Crunsher @dnsmichi @gunnarbeutner @bobapple
CC @carraroj @chrnie @dgoetz @gmimietz @lazyfrosch @lbetz @mkayontour @mwaldmueller @ronny-biering @sngundel @tredel @tschula @widhalmt

**Comment by Al2Klimov** [comment]
@Crunsher Before I write the template for `service-windows`, I'd like you to tell me whether graphing its perfdata makes sense at all.

**Comment by Crunsher** [comment]
perfmon-windows:
Two example calls, please keep in mind I was using localized performance counter names.
```
>.\check_perfmon.exe --performance-counter "\Prozessor(_Total)\Leerlaufzeit (%)" -w !70 -c!90
PERFMON OK "\Prozessor(_Total)\Leerlaufzeit (%)" = 99.2188 | "\Prozessor(_Total)\Leerlaufzeit (%)"=99.2188;70;90;;

>.\check_perfmon.exe --performance-counter "\System\Prozesse" -w 100 -c 200
PERFMON OK "\System\Prozesse" = 64 | "\System\Prozesse"=64;100;200;;

```
service-windows:
Yes, it makes sense to graph it to monitor the uptime of a service, please come to me if there are any problems with the performance output

**Comment by Al2Klimov** [comment]
As discussed w/ @Crunsher (offline):

`check_service.exe` yields [dwCurrentState](https://msdn.microsoft.com/en-us/library/windows/desktop/ms685996(v=vs.85).aspx) which is not a typically graphable value series – e.g. `check_network.exe` gives you a graph which you can easily scan w/ your eyes, but this one... :/

@bobapple What do you think about this? Our options are:
1. Graphing as is
2. Not providing any templates (and letting the default one do its thing)
3. Disabling the graph explicitly (surprises the user)
4. Transforming the numbers so that the highest possible value stands for "Service is running" and the lowest possible value stands for some error (surprises the user?)

**Comment by bobapple** [comment]
As discussed ,we're not providing a template for `check_service.exe`

**Comment by Hipska** [comment]
What about templates for `ido`, `cluster` (and `cluster-zone`)? As there is also a template for `icinga` and it looks like some data has the same name so some already existing templates can be re-used.

**Comment by drsect0r** [comment]
Consider having templates for the SNMP plugins covered in the following repository: https://github.com/dnsmichi/manubulon-snmp

**Comment by Al2Klimov** [comment]
Can we close this one?

**Comment by Hipska** [comment]
Could this get an answer please?
> What about templates for `ido`, `cluster` (and `cluster-zone`)? As there is also a template for `icinga` and it looks like some data has the same name so some already existing templates can be re-used.

**Comment by Al2Klimov** [comment]
@Hipska Sorry, I've overseen that.

@bobapple What's your opinion on this? (You've made [the requirements list](https://github.com/Icinga/icingaweb2-module-graphite/issues/71#issue-267189874) after all.)

**Comment by dnsmichi** [comment]
I would do the following with the remaining requests:

- Create new issues specifically for each template
- Add an URL to template guidelines/examples in there
- Put the "help wanted" label on them

**Comment by Al2Klimov** [comment]
Note: Despite whether we close this one or not, feel free to create and contribute missing templates if you're familiar with the respective check command. You're likely to be faster then us – and the faster the template is created, the faster it's included in the next release. (Icinga 2 accepts check command config for "non official" plugins, too after all.)

**Comment by bobapple** [comment]
I agree with @dnsmichi's proposal to create an issue for each missing template 👍

**Comment by Al2Klimov** [comment]
... which can be also done by whoever misses the respective template.
